project:
  type: website
  output-dir: docs

website:
  title: "Obesity Level Analysis Report"
  navbar:
    background: primary
    search: true
    left:
      - text: "EDA"
        file: Scripts/eda.qmd
      - text: "Modelling"
        file: Scripts/modelling.qmd
      - text: "Evaluation"
        file: Scripts/evaluation.qmd

format:
  html:
    theme: cosmo 
    toc: true
    toc-depth: 2
    number-sections: true
    code-fold: true
    code-tools: true
    code-summary: "Show Code"
    fig-cap-location: top
    fig-align: center
    css: styles.css
